### ISSUE TITLE
unable to hide filters

### ISSUE THREAD

**Issue by blondie63** [joomla-extensions/weblinks#469]
### Steps to reproduce the issue
I'm using last 4.0 here: https://dolcevita.bar/it/menu

### Expected result
<img width="858" alt="weblinks-filter-bug" src="https://user-images.githubusercontent.com/1261851/135654186-0a21af8e-8adc-40a0-bd8c-7090b92d50c3.png">

### System information (as much as possible)
JM 4.0.3
Weblinks 4.0

**Comment by joomdonation** [comment]
@blondie63

There was a typo and it was fixed on this commit https://github.com/joomla-extensions/weblinks/commit/27d8fdc7ce874b202742462130f5e4452dc039ab

You can update your site to the attached package of weblinks [pkg-weblinks-4.0.0.zip](https://github.com/joomla-extensions/weblinks/files/7270948/pkg-weblinks-4.0.0.zip) , then you should be able to hide that filter by editing the menu item, set Filter Field parameter to Hide (see attached screenshot)

![menu_item_params](https://user-images.githubusercontent.com/977664/135705775-ca7269ba-1c34-4795-a5b4-29ae538368a6.png)


For changing the icon, access to weblinks component, then press Options in the toolbar and select the icon you want (see the screenshot)

![weblin_icon](https://user-images.githubusercontent.com/977664/135705832-30a0b195-f113-4d7f-943a-6b3ad4ccc998.png)


You can choose up to two images for each weblinks. Not sure what's the problem when you trying to select images for weblink?

**Comment by blondie63** [comment]
ok i've updated with zip you added here, going to menu item and saving setting over, now filter row disappear!
But there are still some problems:
1. i set field "Text/Icon/Web Link Only" = Web Link Only but a left icon still appear
2. i'd like to have different icon for each Link so i set one image on link "Carta dei Vini" and set First Image Float = Left but no image appear -> https://dolcevita.bar/it/menu

**Comment by joomdonation** [comment]
@blondie63 

1. Confirm the isssue. Ping @chmst for looking at this since she worked in the layout part
2. We do not support different icon for each Link. For the First Image, it will only be displayed if there is Description for weblink. Without description, it won't be displayed (I don't know the reason, but it has been working like that before, same with Joomla 3)

For your need, I guess you will have to implement a layout override. So:

- Select the icon for the First Image of the weblink
- And implement the override to display that first image as the icon for weblink

The layout file to override is components/com_weblinks/tmpl/category/default_items.php
